#!/usr/bin/perl

sub basicescape {
    s#&#&apm;#g;
    s#<#&lt;#g;
    s#>#&gt;#g;
}

sub tagify {
# Put quoted text to italic
    s#^&gt;(.*)#<I>&gt;$1</I>#g;
# Transform url's to hrefs
    s#([a-z]*://\S*)#<A HREF="$1">$1</A>#g;
# Transform mail adresses to hrefs
    s#([-a-zA-Z._0-9]+\@[-a-zA-Z._0-9]+)#<A HREF="mailto:$1">$1</A>#g;
# Transform <file.h> into hrefs
    s#&lt;(\S+\.h)&gt;#<A HREF="file:/usr/include/$1">&lt;$1&gt;</A>#g;
# Transform /path/path/path into hrefs
    s# (/[a-z]+/[a-z.-/]+)# <A HREF="file:$1">$1</A>#g;
}

sub plain {
}

$_ = $ARGV[1];
if (/^text.html/) {
} else {
    exit(1);
}    

print "<HTML><BODY>\n";

$_ = $ARGV[0];
if (/^text.plain/) {
    print "<PRE>";
    while( <STDIN> ) {
	basicescape();
	tagify();
	print "$_";
    }
    print "</PRE>";
} 

if (/^internal.lynx-news/) {
    while( <STDIN> ) {
	if (/<XMP>/) {
	    print "<HTML><HEAD><TITLE>News article</TITLE></HEAD><BODY><PRE>";
	    last;
	}
	print "$_";
    }
    $first = 1;
    $skip = 0;
    while( <STDIN> ) {
	if ($skip) { $skip--; next; }
	$first = 0;

	basicescape();
        s:>+(\S+\@[-a-zA-Z._0-9]*):<A HREF=\"mailto\:$1\">$1</A>:;
	s#From:(.*)#<B>From:$1</B>#;
	s#Subject:(.*)#<B>Subject:$1</B>#;
        s#(\S+\@[-a-zA-Z._0-9]*)#<A HREF="mailto:$1">$1</A>#;
	if (/^Mime-Version/) { next; }
	if (/^Message-ID/) { next; }
	if (/^NNTP-Posting-Host/) { next; }
	if (/^Content-Type/) { next; }
	if (/^Lines/) { next; }
	if (/^Newsgroups/) { 
	    s#([a-zA-Z]*\.[a-zA-Z.]*)#<A HREF="$1">$1</A>#g;
	}
	if (/^Path/) { $skip = 1; next; }

	if (/^\s*$/) { print "\n\n"; last; }
	print "$_";
    }
    while( <STDIN> ) {
	basicescape();
	tagify();
	s#&lt;/XMP&gt;#</PRE>#;
	print "$_";
    }
}

print "<HR><P ALIGN=right><I>[$ARGV[2]: $ARGV[0] -&gt; $ARGV[1]]</I></BODY></HTML>";
